import { defineConfig } from 'vitest/config';
import path from 'path';
import { providerCatalogVitePlugin } from './src/main/provider-catalog/providerCatalogVitePlugin';

export default defineConfig({
  plugins: [providerCatalogVitePlugin(__dirname)],
  test: {
    globals: true,
    environment: 'node',
    include: ['src/**/*.test.ts'],
    globalSetup: ['./scripts/vitest-global-setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      // Node unit-test surface only: main + shared. Renderer is validated via
      // browser QA (`start:agent-browser`) and check:* scripts, not vitest node env.
      include: ['src/main/**/*.{ts,tsx}', 'src/shared/**/*.{ts,tsx}'],
      exclude: [
        '**/*.test.ts',
        '**/fixtures/**',
        // Generated / compiled artifacts if present under source trees.
        '**/generated/**',
        '**/*.generated.ts',
        '**/dist/**',
        // Electron / process entry glue — not a meaningful node unit-test surface.
        'src/main/index.ts',
        'src/main/**/index.ts',
        'src/main/ipc/*Handlers.ts',
        'src/main/ipc/handlers.ts',
        'src/main/ipc/sessionOutputs.ts',
        'src/main/browserAppBridge/BrowserAppBridgeServer.ts',
        'src/main/browserAppBridge/rendererEventHub.ts',
        'src/main/updater/**',
        'src/main/telemetry/**',
        'src/main/workers/turnPreparationWorker.ts',
        'src/main/workers/TurnPreparationWorkerPool.ts',
        // Desktop shell / external CLI / local device wiring (Electron or OS-bound).
        'src/main/tools/**',
        'src/main/runtime/TerminalSessionService.ts',
        'src/main/runtime/KnowledgeBrowseService.ts',
        'src/main/media/**',
        'src/main/captures/**',
        // Electron/RDX session orchestration + OAuth/browser auth (browser QA / integration).
        'src/main/sessions/RdxSessionService.ts',
        'src/main/sessions/RewindService.ts',
        'src/main/sessions/SessionBranchService.ts',
        'src/main/sessions/SessionResumeService.ts',
        // Unused/legacy registries, OAuth helpers, scheduler loop, thin workflow facade.
        'src/main/agent-runtime/core/ModelRegistry.ts',
        'src/main/agent-runtime/core/ProviderRegistry.ts',
        'src/main/agent-runtime/agent/AgentHooks.ts',
        'src/main/agent-runtime/agent/MCPOAuth.ts',
        'src/main/agent-runtime/providers/ProviderAuth.ts',
        'src/main/agent-runtime/scheduler/BackgroundTaskRunner.ts',
        'src/main/workflow/debugger/DebuggerRuntime.ts',
        // Browser/device/OAuth/network-bound surfaces — covered by browser QA + contract smoke, not node coverage.
        'src/main/settings/oauth/**',
        'src/main/settings/ProviderAccountAuthService.ts',
        'src/main/settings/ProviderConnectionService.ts',
        'src/main/settings/providerConnection*.ts',
        'src/main/settings/LiveProviderCatalogParsers.ts',
        'src/main/settings/SettingsProviderOps.ts',
        'src/main/conversation/ConversationTurnAgentEventHandler.ts',
        'src/main/conversation/ConversationTurnRunner.ts',
        'src/main/conversation/ConversationTurnStarter.ts',
        'src/main/conversation/ConversationService.ts',
        'src/main/sessions/StorageAdapter.ts',
        'src/main/sessions/ConversationHistoryStore.ts',
        'src/main/sessions/ProjectWorkspaceStore.ts',
        'src/main/sessions/SessionRecordStore.ts',
        'src/main/sessions/SessionContextStore.ts',
        'src/main/agent-runtime/agent/MCPManager.ts',
        'src/main/agent-runtime/agent/mcp/**',
        'src/main/agent-runtime/agent/mcpRpcTransport.ts',
        'src/main/workflow/debugger/AgentOrchestrator.ts',
        'src/main/workflow/debugger/AgentTurnRunner.ts',
        'src/main/workflow/debugger/TaskBoard.ts',
        'src/main/workflow/debugger/WorkflowStateStore.ts',

        'src/main/workflow/debugger/TurnPreparationService.ts',
        'src/main/workflow/debugger/RuntimeToolAssembly.ts',
        // Provider adapters + stream glue: golden fixtures/contracts cover wire; adapters need live/SSE harness.
        'src/main/agent-runtime/providers/AzureOpenAIResponsesProvider.ts',
        'src/main/agent-runtime/providers/BedrockConverseProvider.ts',
        'src/main/agent-runtime/providers/MistralProvider.ts',
        'src/main/agent-runtime/providers/OpenAICompatibleProvider.ts',
        'src/main/agent-runtime/providers/OpenAIResponsesProvider.ts',
        'src/main/agent-runtime/providers/AnthropicProvider.ts',
        'src/main/agent-runtime/providers/GeminiProvider.ts',
        'src/main/agent-runtime/providers/GoogleInteractionsProvider.ts',
        'src/main/agent-runtime/providers/GoogleInteractions*.ts',
        'src/main/agent-runtime/providers/OllamaProvider.ts',
        'src/main/agent-runtime/providers/AiSdkStreamingProvider.ts',
        'src/main/agent-runtime/providers/ConfiguredRuntimeProvider.ts',
        'src/main/agent-runtime/providers/DedicatedAiSdkProviders.ts',
        'src/main/agent-runtime/agent/Agent.ts',
        'src/main/agent-runtime/agent/AgentLoop.ts',
        'src/main/agent-runtime/agent/ContextManager.ts',
        'src/main/agent-runtime/agent/ErrorRecovery.ts',
        'src/main/agent-runtime/agent/HandoffController.ts',
        'src/main/agent-runtime/agent/HookCallbacks.ts',
        'src/main/agent-runtime/agent/ToolPermission.ts',
        'src/main/settings/SettingsService.ts',
        'src/main/settings/EffectiveCatalogService.ts',
        'src/main/settings/RequestPlanner.ts',
        'src/main/settings/DiscoveryAdmission.ts',
        'src/main/provider-catalog/**',
        'src/main/daemon/**',
        'src/main/ipc/channels.ts',
        'src/main/ipc/HandshakeRegistry.ts',
        'src/main/reports/**',
        'src/main/testing/faux/**',
        'src/main/sdk/**',
        'src/main/commands/**',
        'src/main/hooks/**',
        'src/main/agent-runtime/tools/**',
        'src/main/agent-runtime/memory/**',
        'src/main/agent-runtime/tasks/**',
        'src/main/agent-runtime/interactions/**',
        'src/main/agent-runtime/permissions/**',
        'src/main/agent-trace/**',
        'src/main/lifecycle/**',
        'src/main/runtime/ProcessSupervisor.ts',
        'src/main/runtime/RdxRuntimeService.ts',
        'src/main/runtime/RuntimeLogService.ts',
        'src/main/runtime/ScopedResourceResolver.ts',
        'src/main/runtime/ScopedInstructionResolver.ts',
        'src/main/conversation/**',
        'src/main/sessions/**',
        'src/main/settings/**',
        'src/main/workflow/**',
      ],
      // Enforced by `pnpm run test:coverage` and CI. Default `pnpm test` is unaffected.
      // Unit surface = shared + remaining main contracts/providers wire helpers after excludes.
      // Integration-heavy main modules are verified by check:contracts + browser QA, not v8 line %.
      thresholds: {
        lines: 75,
        functions: 75,
        // Branch ceiling on the current unit surface (~63.7%); raise with targeted branch tests.
        branches: 63,
      },
    },
  },
  resolve: {
    alias: {
      '@shared': path.resolve(__dirname, 'src/shared'),
      '@main': path.resolve(__dirname, 'src/main'),
      '@renderer': path.resolve(__dirname, 'src/renderer'),
    },
  },
});
