export type AgentWorkbenchToolPermission =
  | 'readonly'
  | 'mutation'
  | 'destructive'
  | 'approval';

export interface AgentWorkbenchToolDeclaration {
  id: string;
  label: string;
  permission: AgentWorkbenchToolPermission;
  inputSchema: Record<string, unknown>;
  resultSummary: string;
  icon: string;
  approvalRequired: boolean;
}

export interface AgentWorkbenchCommandDeclaration {
  command: string;
  label: string;
  description: string;
  relatedTools: string[];
  permission: AgentWorkbenchToolPermission;
}

export const AGENT_WORKBENCH_TOOL_CATALOG: AgentWorkbenchToolDeclaration[] = [
  {
    id: 'read_file',
    label: 'Read File',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['path'], properties: { path: { type: 'string' } } },
    resultSummary: 'Returns text content from a workspace file.',
    icon: 'file-text',
    approvalRequired: false,
  },
  {
    id: 'read_image',
    label: 'Read Image',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['path'], properties: { path: { type: 'string' } } },
    resultSummary: 'Reads a workspace image for vision-capable routes.',
    icon: 'image',
    approvalRequired: false,
  },
  {
    id: 'glob',
    label: 'Glob',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['pattern'], properties: { pattern: { type: 'string' } } },
    resultSummary: 'Lists workspace paths matching a glob pattern.',
    icon: 'folder-search',
    approvalRequired: false,
  },
  {
    id: 'grep',
    label: 'Grep',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['pattern'], properties: { pattern: { type: 'string' }, path: { type: 'string' } } },
    resultSummary: 'Returns matching text locations from workspace files.',
    icon: 'search',
    approvalRequired: false,
  },
  {
    id: 'web_fetch',
    label: 'Web Fetch',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['url'], properties: { url: { type: 'string' } } },
    resultSummary: 'Fetches public HTTP(S) page text.',
    icon: 'globe',
    approvalRequired: false,
  },
  {
    id: 'web_search',
    label: 'Web Search',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['query'], properties: { query: { type: 'string' } } },
    resultSummary: 'Searches public web results.',
    icon: 'search-check',
    approvalRequired: false,
  },
  {
    id: 'shell',
    label: 'Shell',
    permission: 'approval',
    inputSchema: { type: 'object', required: ['command'], properties: { command: { type: 'string' } } },
    resultSummary: 'Runs an approved workspace command and returns stdout/stderr.',
    icon: 'terminal',
    approvalRequired: true,
  },
  {
    id: 'write_file',
    label: 'Write File',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['path', 'content'], properties: { path: { type: 'string' }, content: { type: 'string' } } },
    resultSummary: 'Writes a workspace file after policy approval.',
    icon: 'file-plus',
    approvalRequired: true,
  },
  {
    id: 'edit_file',
    label: 'Edit File',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['path'], properties: { path: { type: 'string' }, patch: { type: 'string' } } },
    resultSummary: 'Edits a workspace file after policy approval.',
    icon: 'pencil',
    approvalRequired: true,
  },
  {
    id: 'delete_file',
    label: 'Delete File',
    permission: 'destructive',
    inputSchema: { type: 'object', required: ['path'], properties: { path: { type: 'string' } } },
    resultSummary: 'Deletes a workspace file after policy approval.',
    icon: 'file-x',
    approvalRequired: true,
  },
  {
    id: 'move_file',
    label: 'Move File',
    permission: 'mutation',
    inputSchema: {
      type: 'object',
      required: ['source', 'destination'],
      properties: { source: { type: 'string' }, destination: { type: 'string' } },
    },
    resultSummary: 'Moves or renames a workspace file after policy approval.',
    icon: 'file-input',
    approvalRequired: true,
  },
  {
    id: 'copy_file',
    label: 'Copy File',
    permission: 'mutation',
    inputSchema: {
      type: 'object',
      required: ['source', 'destination'],
      properties: { source: { type: 'string' }, destination: { type: 'string' } },
    },
    resultSummary: 'Copies a workspace file after policy approval.',
    icon: 'copy',
    approvalRequired: true,
  },
  {
    id: 'notebook_edit',
    label: 'Notebook Edit',
    permission: 'mutation',
    inputSchema: {
      type: 'object',
      required: ['notebook_path', 'cell_index', 'new_source'],
      properties: {
        notebook_path: { type: 'string' },
        cell_index: { type: 'integer' },
        new_source: { type: 'string' },
      },
    },
    resultSummary: 'Edits a single cell in a Jupyter notebook file.',
    icon: 'notebook',
    approvalRequired: false,
  },
  {
    id: 'git_status',
    label: 'Git Status',
    permission: 'readonly',
    inputSchema: { type: 'object', properties: { short: { type: 'boolean' } } },
    resultSummary: 'Shows git status for the current project repository.',
    icon: 'git-branch',
    approvalRequired: false,
  },
  {
    id: 'git_diff',
    label: 'Git Diff',
    permission: 'readonly',
    inputSchema: {
      type: 'object',
      properties: { path: { type: 'string' }, staged: { type: 'boolean' }, stat: { type: 'boolean' } },
    },
    resultSummary: 'Shows git diff for the current project repository.',
    icon: 'git-compare',
    approvalRequired: false,
  },
  {
    id: 'git_log',
    label: 'Git Log',
    permission: 'readonly',
    inputSchema: { type: 'object', properties: { limit: { type: 'integer' } } },
    resultSummary: 'Shows recent git commits for the current project repository.',
    icon: 'git-commit',
    approvalRequired: false,
  },
  {
    id: 'git_add',
    label: 'Git Add',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['path'], properties: { path: { type: 'string' } } },
    resultSummary: 'Stages a repository-relative path.',
    icon: 'git-branch',
    approvalRequired: true,
  },
  {
    id: 'git_unstage',
    label: 'Git Unstage',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['path'], properties: { path: { type: 'string' } } },
    resultSummary: 'Unstages a repository-relative path.',
    icon: 'git-branch',
    approvalRequired: true,
  },
  {
    id: 'git_commit',
    label: 'Git Commit',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['message'], properties: { message: { type: 'string' } } },
    resultSummary: 'Creates a git commit from staged changes.',
    icon: 'git-commit',
    approvalRequired: true,
  },
  {
    id: 'task_list',
    label: 'Tasks',
    permission: 'readonly',
    inputSchema: { type: 'object', properties: {} },
    resultSummary: 'Summarizes current task or plan state.',
    icon: 'list-checks',
    approvalRequired: false,
  },
  {
    id: 'task_create',
    label: 'Create Tasks',
    permission: 'mutation',
    inputSchema: {
      type: 'object',
      required: ['tasks'],
      properties: {
        tasks: {
          type: 'array',
          minItems: 1,
          items: {
            type: 'object',
            required: ['subject'],
            properties: {
              subject: { type: 'string' },
              description: { type: 'string' },
              blockedBy: { type: 'array', items: { type: 'string' } },
            },
          },
        },
      },
    },
    resultSummary: 'Creates the full private agent task list in one call.',
    icon: 'list-plus',
    approvalRequired: false,
  },
  {
    id: 'task_update',
    label: 'Update Task',
    permission: 'mutation',
    inputSchema: {
      type: 'object',
      required: ['taskId'],
      properties: {
        taskId: { type: 'string' },
        status: { type: 'string' },
        subject: { type: 'string' },
        description: { type: 'string' },
      },
    },
    resultSummary: 'Updates status or metadata for a private agent task record.',
    icon: 'list-todo',
    approvalRequired: false,
  },
  {
    id: 'task_get',
    label: 'Get Task',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['taskId'], properties: { taskId: { type: 'string' } } },
    resultSummary: 'Reads a private agent task record by id.',
    icon: 'list',
    approvalRequired: false,
  },
  {
    id: 'task_stop',
    label: 'Stop Task',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['taskId'], properties: { taskId: { type: 'string' } } },
    resultSummary: 'Stops a running private agent task.',
    icon: 'list-x',
    approvalRequired: false,
  },
  {
    id: 'ask_user',
    label: 'Ask User',
    permission: 'approval',
    inputSchema: {
      type: 'object',
      required: ['questions'],
      properties: {
        questions: {
          type: 'array',
          minItems: 1,
          items: {
            type: 'object',
            required: ['prompt'],
            properties: {
              questionId: { type: 'string' },
              prompt: { type: 'string' },
              description: { type: 'string' },
              allowFreeform: { type: 'boolean' },
              options: {
                type: 'array',
                items: {
                  type: 'object',
                  required: ['label'],
                  properties: {
                    optionId: { type: 'string' },
                    label: { type: 'string' },
                    description: { type: 'string' },
                  },
                },
              },
            },
          },
        },
      },
    },
    resultSummary: 'Surfaces one or more user questions and resolves them as structured answers.',
    icon: 'message-question',
    approvalRequired: false,
  },
  {
    id: 'agent_handoff',
    label: 'Agent Handoff',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['agent'], properties: { agent: { type: 'string' }, label: { type: 'string' }, prompt: { type: 'string' } } },
    resultSummary: 'Creates an implementation or specialist handoff summary.',
    icon: 'route',
    approvalRequired: false,
  },
  {
    id: 'subagent',
    label: 'Subagent',
    permission: 'readonly',
    inputSchema: {
      type: 'object',
      required: ['task'],
      properties: {
        task: { type: 'string' },
        profile: { type: 'string' },
        model: { type: 'string' },
      },
    },
    resultSummary: 'Delegates a sub-task to an isolated sub-agent and returns its answer.',
    icon: 'bot',
    approvalRequired: false,
  },
  {
    id: 'memory_search',
    label: 'Search Memory',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['scope'], properties: { scope: { type: 'string', enum: ['user', 'project'] }, query: { type: 'string' }, limit: { type: 'number' } } },
    resultSummary: 'Searches explicitly saved memories in one declared scope.',
    icon: 'brain',
    approvalRequired: false,
  },
  {
    id: 'memory_read',
    label: 'Memory',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['scope', 'name'], properties: { scope: { type: 'string', enum: ['user', 'project'] }, name: { type: 'string' } } },
    resultSummary: 'Reads one explicitly saved memory by scope and name.',
    icon: 'brain',
    approvalRequired: false,
  },
  {
    id: 'memory_write',
    label: 'Write Memory',
    permission: 'mutation',
    inputSchema: {
      type: 'object',
      required: ['scope', 'name', 'description', 'type', 'content', 'approved'],
      properties: {
        scope: { type: 'string', enum: ['user', 'project'] },
        name: { type: 'string' },
        description: { type: 'string' },
        type: { type: 'string' },
        content: { type: 'string' },
        tags: { type: 'array', items: { type: 'string' } },
        approved: { type: 'boolean' },
      },
    },
    resultSummary: 'Persists an explicitly approved memory to one declared scope.',
    icon: 'brain',
    approvalRequired: true,
  },
  {
    id: 'memory_delete',
    label: 'Delete Memory',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['scope', 'name', 'confirmed'], properties: { scope: { type: 'string', enum: ['user', 'project'] }, name: { type: 'string' }, confirmed: { type: 'boolean' } } },
    resultSummary: 'Deletes one scoped memory after explicit confirmation.',
    icon: 'brain',
    approvalRequired: true,
  },
  {
    id: 'plan_artifact',
    label: 'Plan Artifact',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['content'], properties: { title: { type: 'string' }, content: { type: 'string' } } },
    resultSummary: 'Writes the current plan to the active session artifact.',
    icon: 'file-check',
    approvalRequired: false,
  },
  {
    id: 'output_register',
    label: 'Publish Output',
    permission: 'mutation',
    inputSchema: { type: 'object', required: ['path'], properties: { path: { type: 'string' }, title: { type: 'string' }, kind: { type: 'string' } } },
    resultSummary: 'Publishes one explicit project file as a user-visible session output.',
    icon: 'file-export',
    approvalRequired: false,
  },
  {
    id: 'skills',
    label: 'Skills',
    permission: 'readonly',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
    resultSummary: 'Lists configured reusable skills.',
    icon: 'sparkles',
    approvalRequired: false,
  },
  {
    id: 'skill_read',
    label: 'Read Skill',
    permission: 'readonly',
    inputSchema: { type: 'object', required: ['skill_id'], properties: { skill_id: { type: 'string' } } },
    resultSummary: 'Loads full SKILL.md instructions for one configured skill.',
    icon: 'sparkles',
    approvalRequired: false,
  },
  {
    id: 'mcp',
    label: 'MCP',
    permission: 'readonly',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
    resultSummary: 'Lists configured MCP services.',
    icon: 'plug',
    approvalRequired: false,
  },
  {
    id: 'tool_search',
    label: 'Tool Search',
    permission: 'readonly',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string' },
        category: { type: 'string' },
        requires_approval: { type: 'boolean' },
      },
    },
    resultSummary: 'Searches available tools by name, description, category, or approval requirement.',
    icon: 'search',
    approvalRequired: false,
  },
  {
    id: 'rdx_context',
    label: 'RDX Context',
    permission: 'readonly',
    inputSchema: { type: 'object', properties: {} },
    resultSummary: 'Reads current RDC/RDX runtime context.',
    icon: 'monitor-dot',
    approvalRequired: false,
  },
  {
    id: 'code_interpreter',
    label: 'Code Interpreter',
    permission: 'approval',
    inputSchema: {
      type: 'object',
      required: ['code'],
      properties: {
        code: { type: 'string' },
        language: { type: 'string' },
      },
    },
    resultSummary: 'Runs approved interpreter code in the project workspace and returns stdout plus artifacts.',
    icon: 'terminal-square',
    approvalRequired: true,
  },
];

export const AGENT_WORKBENCH_COMMAND_CATALOG: AgentWorkbenchCommandDeclaration[] = [
  {
    command: '/help',
    label: 'Help',
    description: 'Show available profile commands and tool boundaries.',
    relatedTools: [],
    permission: 'readonly',
  },
  {
    command: '/compact',
    label: 'Compact',
    description: 'Request context compaction when the profile can manage context.',
    relatedTools: ['memory_read'],
    permission: 'readonly',
  },
  {
    command: '/context',
    label: 'Context',
    description: 'Summarize current project, session, captures, and available context.',
    relatedTools: ['read_file', 'memory_read', 'rdx_context'],
    permission: 'readonly',
  },
  {
    command: '/memory',
    label: 'Memory',
    description: 'Inspect profile-accessible memory.',
    relatedTools: ['memory_read', 'plan_artifact', 'task_list'],
    permission: 'readonly',
  },
  {
    command: '/agents',
    label: 'Agents',
    description: 'List profiles and handoff options visible to the current profile.',
    relatedTools: ['agent_handoff'],
    permission: 'readonly',
  },
  {
    command: '/skills',
    label: 'Skills',
    description: 'List configured skills visible to the current profile.',
    relatedTools: ['skills'],
    permission: 'readonly',
  },
  {
    command: '/mcp',
    label: 'MCP',
    description: 'List configured MCP services visible to the current profile.',
    relatedTools: ['mcp'],
    permission: 'readonly',
  },
  {
    command: '/status',
    label: 'Status',
    description: 'Summarize runtime, route, tool, and capture status.',
    relatedTools: ['task_list', 'task_get', 'rdx_context'],
    permission: 'readonly',
  },
  {
    command: '/model',
    label: 'Model',
    description: 'Show or switch the conversation model; use /model default to follow the Agent configuration.',
    relatedTools: [],
    permission: 'readonly',
  },
];
