import type { GenerativeUiBenchmarkCase, GenerativeUiBenchmarkCategory } from '../types/generativeUi';

const build = (caseId: string, category: GenerativeUiBenchmarkCategory, title: string, prompt: string, requiredInteractions: string[], requiredEvidence: string[]): GenerativeUiBenchmarkCase =>
  ({ caseId, category, title, prompt, requiredInteractions, requiredEvidence });

export const GENERATIVE_UI_BENCHMARK_VERSION = 'v1.0.0';
export const GENERATIVE_UI_BENCHMARK_CASES: GenerativeUiBenchmarkCase[] = [
  build('website-local-clinic', 'website', 'Local clinic website', 'Create a trustworthy responsive website for a neighborhood clinic with service navigation, doctor profiles, appointment request flow, FAQ disclosure, validation, and accessible mobile navigation. Use realistic inline data and no external assets.', ['navigate services', 'submit appointment form', 'open FAQ'], ['desktop and narrow layout', 'validation feedback']),
  build('website-event-launch', 'website', 'Product event launch', 'Design an event launch site with schedule filtering, speaker details, ticket tier comparison, countdown behavior, and a registration CTA. It must remain usable with long speaker names and at 375px width.', ['filter schedule', 'open speaker', 'select ticket tier'], ['responsive navigation', 'interactive schedule']),
  build('website-learning-course', 'website', 'Course landing experience', 'Build a course landing experience that lets learners inspect modules, preview lessons, compare plans, calculate weekly study load, and enroll through a validated form.', ['expand module', 'change study hours', 'submit enrollment'], ['keyboard navigation', 'computed study plan']),
  build('website-travel-itinerary', 'website', 'Travel itinerary builder', 'Create a three-day city itinerary builder with day tabs, activity selection, budget totals, dietary filters, and a printable summary. All data must be embedded.', ['switch day', 'toggle activity', 'filter dietary needs'], ['live budget total', 'print-friendly structure']),
  build('dashboard-operations', 'dashboard', 'Operations dashboard', 'Create an operations dashboard for fulfillment teams with KPI cards, date and region filters, sortable exception table, drill-down details, and clear loading/empty/error states using embedded data.', ['change region', 'sort table', 'open exception'], ['linked KPI updates', 'narrow table behavior']),
  build('dashboard-energy', 'dashboard', 'Energy monitoring dashboard', 'Build an energy monitoring dashboard with hourly consumption, renewable share, anomaly markers, building selector, cost projection, and an accessible legend. Generate charts with native SVG or Canvas.', ['select building', 'toggle series', 'inspect anomaly'], ['chart semantics', 'computed projection']),
  build('dashboard-product', 'dashboard', 'Product analytics dashboard', 'Create a product analytics dashboard showing activation funnel, cohort retention, feature adoption, and segment comparison. Filters must update every linked view and preserve readable empty states.', ['change segment', 'change date range', 'inspect cohort'], ['cross-filter consistency', 'responsive charts']),
  build('simulator-pricing', 'simulator', 'SaaS pricing simulator', 'Build a SaaS pricing simulator where users adjust seats, usage, support tier, annual billing, and discount assumptions; show monthly and annual totals, break-even guidance, and a shareable scenario summary.', ['adjust seats', 'change tier', 'toggle annual billing'], ['deterministic totals', 'scenario summary']),
  build('simulator-retirement', 'simulator', 'Retirement scenario simulator', 'Create an educational retirement scenario simulator with starting balance, contributions, years, return and inflation assumptions, deterministic projection, comparison scenarios, and clear non-advice disclosure.', ['adjust assumptions', 'add comparison', 'reset scenario'], ['deterministic projection', 'accessible disclosure']),
  build('simulator-queue', 'simulator', 'Service queue simulator', 'Build a deterministic service queue simulator with arrival rate, service rate, server count, seeded randomness, run/pause/reset controls, timeline chart, wait-time distribution, and overload explanation.', ['run simulation', 'pause simulation', 'change server count'], ['seeded reproducibility', 'overload state']),
  build('tool-json-explorer', 'tool', 'JSON explorer', 'Create an offline JSON explorer with paste input, parse errors, collapsible tree, key search, path copying, summary counts, and a sample payload button. Never execute pasted content.', ['parse JSON', 'search keys', 'copy path'], ['invalid JSON handling', 'large tree usability']),
  build('tool-color-contrast', 'tool', 'Color contrast tool', 'Build a color contrast checker with foreground/background pickers, text preview, WCAG ratio calculation, AA/AAA results, swap/reset actions, and suggested accessible alternatives.', ['change colors', 'swap colors', 'apply suggestion'], ['correct ratio', 'non-color status']),
  build('tool-regex-lab', 'tool', 'Regex learning lab', 'Create a safe regex learning lab with pattern, flags, test text, highlighted matches, capture groups, common examples, invalid-pattern errors, and guardrails against freezing on pathological input.', ['edit pattern', 'toggle flags', 'load example'], ['error recovery', 'match details']),
  build('tool-kanban', 'tool', 'Personal kanban prototype', 'Build an offline kanban prototype with three columns, add/edit/delete cards, drag or keyboard movement, filters, counts, undo for deletion, and persistence only within the running page memory.', ['add card', 'move card', 'undo deletion'], ['keyboard alternative', 'filter counts']),
  build('visualization-network', 'visualization', 'Dependency network explorer', 'Create an interactive dependency network explorer from embedded nodes and edges using native SVG. Support zoom, selection, connected-node emphasis, search, legend, and a readable details panel.', ['search node', 'select node', 'zoom graph'], ['SVG accessibility', 'selection details']),
  build('visualization-budget', 'visualization', 'Budget flow visualization', 'Build an interactive household budget flow visualization with editable categories, income allocation, Sankey-like native SVG, warnings for over-allocation, scenario comparison, and tabular fallback.', ['edit allocation', 'add category', 'compare scenario'], ['allocation validation', 'table fallback']),
  build('visualization-timeline', 'visualization', 'Historical timeline explorer', 'Create an interactive historical timeline with era zoom, category filters, event selection, long multilingual titles, keyboard navigation, and a compact mobile list alternative.', ['filter category', 'select event', 'change era'], ['long text handling', 'mobile alternative']),
  build('game-memory', 'game', 'Accessible memory game', 'Create a polished accessible memory matching game with a 4x4 board, keyboard control, move timer, restart, deterministic seeded deal, win state, and reduced-motion support.', ['flip card', 'restart game', 'complete match'], ['keyboard play', 'win state']),
  build('game-logic-grid', 'game', 'Logic grid puzzle', 'Build a small logic-grid puzzle with clues, tri-state cells, contradiction detection, hint system, reset, completion validation, and an explanation of the solved reasoning.', ['toggle cell', 'request hint', 'validate solution'], ['contradiction state', 'completion feedback']),
  build('game-resource', 'game', 'Resource strategy prototype', 'Create a five-turn resource strategy prototype where players allocate workers among food, research, and defense; show deterministic consequences, event log, undo before commit, and end-state scoring.', ['allocate worker', 'commit turn', 'undo allocation'], ['deterministic turn results', 'final score']),
];
