export const LEFT_SIDEBAR_DEFAULT_WIDTH = 256;
export const LEFT_SIDEBAR_MIN_WIDTH = 220;
export const LEFT_SIDEBAR_MAX_WIDTH = 420;
export const LEFT_SIDEBAR_COLLAPSED_WIDTH = 0;

export const RIGHT_PANEL_DEFAULT_WIDTH = 312;
export const RIGHT_PANEL_MIN_WIDTH = 280;
export const RIGHT_PANEL_MAX_WIDTH = 520;
export const RIGHT_PANEL_COLLAPSED_WIDTH = 0;

export const APP_MIN_MAIN_WIDTH = 480;
export const APP_RESIZE_HANDLE_WIDTH = 8;

export const TERMINAL_DEFAULT_HEIGHT = 328;
export const TERMINAL_MIN_HEIGHT = 180;
export const TERMINAL_MAX_HEIGHT = 720;
