import type {
  BuiltinLlmProviderId,
  LlmProviderAuthMode,
  LlmProviderCatalogGroup,
  LlmProviderEntry,
  LlmProviderKind,
  LlmProviderModel,
  LlmProviderModelDiscoveryStrategy,
} from '@shared/types/settings';

export interface BuiltinProviderDefinition {
  id: BuiltinLlmProviderId;
  kind: LlmProviderKind;
  authMode: LlmProviderAuthMode;
  catalogGroup: LlmProviderCatalogGroup;
  modelDiscovery: LlmProviderModelDiscoveryStrategy | null;
  label: string;
  baseUrl?: string;
  baseUrlEditable?: boolean;
  docsUrl?: string;
  recommendedModels: string[];
  accountLoginConfigured?: boolean;
  unavailableReason?: string;
}

const ANTHROPIC_ALIAS_MODELS = ['sonnet', 'opus', 'haiku'];
const ANTHROPIC_FIRST_PARTY_MODELS = ['sonnet', 'opus'];
export const CLAUDE_ACCOUNT_MODELS = [
  'claude-opus-4-7',
  'claude-sonnet-4-6',
  'claude-haiku-4-5-20251001',
];
export const CHATGPT_ACCOUNT_MODELS = [
  'gpt-5.5',
  'gpt-5.4',
  'gpt-5.4-mini',
  'gpt-5.3-codex',
  'gpt-5.2-codex',
  'gpt-5.1-codex',
  'gpt-5',
  'o4-mini',
  'o3',
  'gpt-4o',
];
export const GITHUB_COPILOT_ACCOUNT_MODELS = [
  'gpt-5.5',
  'gpt-5.4',
  'gpt-5.4-mini',
  'gpt-5.3-codex',
  'gpt-5.2-codex',
  'gpt-5.2',
  'gpt-5-mini',
  'claude-opus-4-7',
  'claude-sonnet-4-6',
  'claude-haiku-4-5',
  'claude-opus-4-6',
  'claude-opus-4-5',
  'claude-sonnet-4-5',
  'gpt-4.1',
];
export const GROK_ACCOUNT_MODELS = [
  'grok-4.3',
  'grok-4',
  'grok-code-fast-1',
];
export const GEMINI_ACCOUNT_MODELS = [
  'gemini-2.5-pro',
  'gemini-2.5-flash',
  'gemini-2.0-flash',
];
export const QWEN_ACCOUNT_MODELS = [
  'qwen-plus',
  'qwen-max',
  'qwen3-coder-plus',
];
const OPENAI_CODE_MODELS = ['gpt-5.2', 'gpt-4.1', 'gpt-5-mini'];

export const BUILTIN_LLM_PROVIDER_DEFINITIONS: BuiltinProviderDefinition[] = [
  {
    id: '302ai',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: '302.AI',
    baseUrl: 'https://api.302.ai/v1',
    recommendedModels: ['gpt-4o', 'claude-3-7-sonnet'],
    docsUrl: 'https://302.ai/',
  },
  {
    id: 'azure-openai',
    kind: 'azure-openai',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'azure-openai',
    label: 'Azure OpenAI',
    baseUrl: '',
    baseUrlEditable: true,
    recommendedModels: ['gpt-4.1', 'gpt-5-mini'],
    docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai/',
  },
  {
    id: 'bailian',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Alibaba Cloud Bailian',
    baseUrl: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    recommendedModels: ['qwen3.6-plus', 'qwen3-coder-next', 'qwen3-coder-plus', 'kimi-k2.5', 'glm-5', 'glm-4.7'],
    docsUrl: 'https://bailian.console.aliyun.com/',
  },
  {
    id: 'anthropic',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic',
    label: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    recommendedModels: ANTHROPIC_FIRST_PARTY_MODELS,
    docsUrl: 'https://platform.claude.com/settings/keys',
  },
  {
    id: 'anthropic-thirdparty',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Anthropic-compatible Endpoint',
    baseUrl: '',
    baseUrlEditable: true,
    recommendedModels: ANTHROPIC_ALIAS_MODELS,
    docsUrl: 'https://platform.claude.com/docs/en/api/overview',
  },
  {
    id: 'cerebras',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'Cerebras',
    baseUrl: 'https://api.cerebras.ai/v1',
    recommendedModels: ['llama-4-scout-17b-16e-instruct', 'qwen-3-coder-480b'],
    docsUrl: 'https://cloud.cerebras.ai/',
  },
  {
    id: 'bedrock',
    kind: 'bedrock',
    authMode: 'environment',
    catalogGroup: 'environment',
    modelDiscovery: 'static',
    label: 'Amazon Bedrock',
    recommendedModels: ANTHROPIC_ALIAS_MODELS,
    docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/amazon-bedrock',
  },
  {
    id: 'custom-endpoint',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'OpenAI-compatible Endpoint',
    baseUrl: '',
    baseUrlEditable: true,
    recommendedModels: ['gpt-4.1'],
    docsUrl: 'https://platform.openai.com/docs/api-reference',
  },
  {
    id: 'claude-account',
    kind: 'anthropic',
    authMode: 'account',
    catalogGroup: 'account',
    modelDiscovery: 'account-catalog',
    label: 'Claude Account',
    recommendedModels: CLAUDE_ACCOUNT_MODELS,
    docsUrl: 'https://claude.ai/',
    accountLoginConfigured: true,
  },
  {
    id: 'chatgpt-account',
    kind: 'openai-compatible',
    authMode: 'account',
    catalogGroup: 'account',
    modelDiscovery: 'account-catalog',
    label: 'ChatGPT Account',
    recommendedModels: CHATGPT_ACCOUNT_MODELS,
    docsUrl: 'https://chatgpt.com/',
    accountLoginConfigured: true,
  },
  {
    id: 'deepseek',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/anthropic',
    recommendedModels: ['deepseek-v4-pro', 'deepseek-v4-flash'],
    docsUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'github-copilot',
    kind: 'openai-compatible',
    authMode: 'account',
    catalogGroup: 'account',
    modelDiscovery: 'account-catalog',
    label: 'GitHub Copilot',
    recommendedModels: GITHUB_COPILOT_ACCOUNT_MODELS,
    docsUrl: 'https://github.com/features/copilot',
    accountLoginConfigured: true,
  },
  {
    id: 'grok-account',
    kind: 'openai-compatible',
    authMode: 'account',
    catalogGroup: 'account',
    modelDiscovery: 'account-catalog',
    label: 'Grok Account',
    baseUrl: 'https://api.x.ai/v1',
    recommendedModels: GROK_ACCOUNT_MODELS,
    docsUrl: 'https://grok.com/',
    accountLoginConfigured: true,
    unavailableReason: 'Live Grok account OAuth requires a stable public account authorization contract; this adapter is mock-verifiable until that contract is configured.',
  },
  {
    id: 'gemini-account',
    kind: 'google-ai-studio',
    authMode: 'account',
    catalogGroup: 'account',
    modelDiscovery: 'account-catalog',
    label: 'Gemini Account',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    recommendedModels: GEMINI_ACCOUNT_MODELS,
    docsUrl: 'https://gemini.google.com/',
    accountLoginConfigured: true,
    unavailableReason: 'Live Gemini account OAuth requires a stable public account authorization contract; this adapter is mock-verifiable until that contract is configured.',
  },
  {
    id: 'qwen-account',
    kind: 'openai-compatible',
    authMode: 'account',
    catalogGroup: 'account',
    modelDiscovery: 'account-catalog',
    label: 'Qwen Account',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    recommendedModels: QWEN_ACCOUNT_MODELS,
    docsUrl: 'https://chat.qwen.ai/',
    accountLoginConfigured: true,
    unavailableReason: 'Live Qwen account OAuth requires a stable public account authorization contract; this adapter is mock-verifiable until that contract is configured.',
  },
  {
    id: 'google-ai-studio',
    kind: 'google-ai-studio',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'google-ai-studio',
    label: 'Google AI Studio',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    recommendedModels: ['gemini-2.5-pro', 'gemini-2.5-flash'],
    docsUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'groq',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    recommendedModels: ['openai/gpt-oss-120b', 'llama-3.3-70b-versatile'],
    docsUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'glm-cn',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Zhipu AI GLM (CN)',
    baseUrl: 'https://open.bigmodel.cn/api/anthropic',
    recommendedModels: ['sonnet', 'opus', 'haiku'],
    docsUrl: 'https://open.bigmodel.cn/',
  },
  {
    id: 'glm-global',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Z.ai GLM (Global)',
    baseUrl: 'https://api.z.ai/api/anthropic',
    recommendedModels: ['sonnet', 'opus', 'haiku'],
    docsUrl: 'https://platform.z.ai/',
  },
  {
    id: 'huggingface',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'Hugging Face',
    baseUrl: 'https://router.huggingface.co/v1',
    recommendedModels: ['openai/gpt-oss-120b', 'Qwen/Qwen3-Coder-480B-A35B-Instruct'],
    docsUrl: 'https://huggingface.co/settings/tokens',
  },
  {
    id: 'vertex',
    kind: 'vertex',
    authMode: 'environment',
    catalogGroup: 'environment',
    modelDiscovery: 'static',
    label: 'Google Vertex AI',
    recommendedModels: ANTHROPIC_ALIAS_MODELS,
    docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/google-vertex-ai',
  },
  {
    id: 'kimi-code',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Kimi Code',
    baseUrl: 'https://api.kimi.com/coding/v1',
    recommendedModels: ['kimi-for-coding'],
    docsUrl: 'https://www.kimi.com/code/docs/en/',
  },
  {
    id: 'litellm',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'LiteLLM',
    baseUrl: 'http://localhost:4000',
    recommendedModels: ANTHROPIC_ALIAS_MODELS,
    docsUrl: 'https://docs.litellm.ai/docs/',
  },
  {
    id: 'manifest',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'Manifest',
    baseUrl: 'https://app.manifest.build/v1',
    recommendedModels: ['gpt-4.1'],
    docsUrl: 'https://app.manifest.build/',
  },
  {
    id: 'minimax-cn',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'MiniMax (CN)',
    baseUrl: 'https://api.minimaxi.com/anthropic',
    recommendedModels: ['MiniMax-M2.7'],
    docsUrl: 'https://platform.minimaxi.com/',
  },
  {
    id: 'minimax-global',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'MiniMax (Global)',
    baseUrl: 'https://api.minimax.io/anthropic',
    recommendedModels: ['MiniMax-M2.7'],
    docsUrl: 'https://platform.minimaxi.com/',
  },
  {
    id: 'mistral',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'Mistral',
    baseUrl: 'https://api.mistral.ai/v1',
    recommendedModels: ['mistral-large-latest', 'codestral-latest'],
    docsUrl: 'https://console.mistral.ai/api-keys/',
  },
  {
    id: 'moonshot',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Kimi / Moonshot AI',
    baseUrl: 'https://api.moonshot.cn/anthropic',
    recommendedModels: ['sonnet'],
    docsUrl: 'https://platform.moonshot.cn/console/api-keys',
  },
  {
    id: 'openrouter',
    kind: 'openrouter',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    recommendedModels: ['anthropic/claude-haiku-latest', 'anthropic/claude-sonnet-4.5', 'openai/gpt-5.2'],
    docsUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openai',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    recommendedModels: OPENAI_CODE_MODELS,
    docsUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-eu',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'OpenAI (EU)',
    baseUrl: 'https://eu.api.openai.com/v1',
    recommendedModels: OPENAI_CODE_MODELS,
    docsUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'openai-us',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'OpenAI (US)',
    baseUrl: 'https://us.api.openai.com/v1',
    recommendedModels: OPENAI_CODE_MODELS,
    docsUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'qwen',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'Qwen / DashScope',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    recommendedModels: ['qwen-plus', 'qwen-max'],
    docsUrl: 'https://dashscope.console.aliyun.com/apiKey',
  },
  {
    id: 'siliconflow',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn/v1',
    recommendedModels: ['Qwen/Qwen3-32B', 'deepseek-ai/DeepSeek-V3'],
    docsUrl: 'https://siliconflow.cn/',
  },
  {
    id: 'volcengine',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Volcengine Ark (Doubao)',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding',
    recommendedModels: ['doubao-seed-1-6', 'glm-4.6', 'deepseek-v4-pro', 'kimi-k2.5'],
    docsUrl: 'https://www.volcengine.com/docs/82379/1928262',
  },
  {
    id: 'vercel-ai-gateway',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'Vercel AI Gateway',
    baseUrl: 'https://ai-gateway.vercel.sh/v1',
    recommendedModels: ['openai/gpt-5.2', 'anthropic/claude-sonnet-4.5'],
    docsUrl: 'https://vercel.com/docs/ai-gateway',
  },
  {
    id: 'xai',
    kind: 'openai-compatible',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'openai-compatible',
    label: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    recommendedModels: ['grok-4.3', 'grok-4'],
    docsUrl: 'https://docs.x.ai/',
  },
  {
    id: 'xiaomi-mimo',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Xiaomi MiMo',
    baseUrl: 'https://api.xiaomimimo.com/anthropic',
    recommendedModels: ['mimo-v2.5-pro'],
    docsUrl: 'https://platform.xiaomimimo.com/#/console/api-keys',
  },
  {
    id: 'xiaomi-mimo-token-plan',
    kind: 'anthropic',
    authMode: 'api-key',
    catalogGroup: 'api-key',
    modelDiscovery: 'anthropic-candidate-validation',
    label: 'Xiaomi MiMo Token Plan',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/anthropic',
    recommendedModels: ['mimo-v2.5-pro'],
    docsUrl: 'https://platform.xiaomimimo.com/#/console/plan-manage',
  },
  {
    id: 'ollama',
    kind: 'ollama',
    authMode: 'local',
    catalogGroup: 'local',
    modelDiscovery: 'ollama-tags',
    label: 'Ollama',
    baseUrl: 'http://127.0.0.1:11434/v1',
    recommendedModels: ['qwen2.5-coder:14b', 'llama3.1:8b'],
    docsUrl: 'https://ollama.com/download',
  },
];

export function isBuiltinProviderId(id: string): id is BuiltinLlmProviderId {
  return BUILTIN_LLM_PROVIDER_DEFINITIONS.some((entry) => entry.id === id);
}

export function getBuiltinProviderDefinition(id: string): BuiltinProviderDefinition | null {
  return BUILTIN_LLM_PROVIDER_DEFINITIONS.find((entry) => entry.id === id) ?? null;
}

const toModels = (modelIds: string[]): LlmProviderModel[] =>
  Array.from(new Set(modelIds)).map((modelId) => ({
    id: modelId,
    label: modelId,
    enabled: true,
  }));

export const createBuiltinProviderEntry = (id: BuiltinLlmProviderId): LlmProviderEntry => {
  const definition = getBuiltinProviderDefinition(id);
  if (!definition) {
    throw new Error(`Unknown builtin provider: ${id}`);
  }

  return {
    id: definition.id,
    kind: definition.kind,
    authMode: definition.authMode,
    catalogGroup: definition.catalogGroup,
    modelDiscovery: definition.modelDiscovery,
    label: definition.label,
    enabled: false,
    apiKey: '',
    hasStoredSecret: definition.authMode === 'local' || definition.authMode === 'environment',
    baseUrl: definition.baseUrl,
    baseUrlEditable: definition.baseUrlEditable,
    models: definition.modelDiscovery === 'static' && definition.authMode === 'environment' ? toModels(definition.recommendedModels) : toModels([]),
    recommendedModels: definition.recommendedModels,
    docsUrl: definition.docsUrl,
    status: 'unconfigured',
    accountLoginConfigured: definition.accountLoginConfigured,
    unavailableReason: definition.unavailableReason,
    isConfigured: false,
  };
};

export const createBuiltinProviderEntries = (): LlmProviderEntry[] =>
  BUILTIN_LLM_PROVIDER_DEFINITIONS.map((entry) => createBuiltinProviderEntry(entry.id));
