import * as fs from 'fs';
import * as path from 'path';
import type { ProjectRecord, SessionRecord } from '@shared/types/session';
import { SessionRecordSchema } from './storageSchema';
import type { StorageHost } from './storageHost';

export function readProjectSessions(
  host: StorageHost,
  project: ProjectRecord,
): Array<{ session: SessionRecord; sessionPath: string }> {
  const sessionsRoot = host.projects.ensureProjectSessionsRoot(project);
  if (!fs.existsSync(sessionsRoot)) {
    return [];
  }

  return fs.readdirSync(sessionsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const sessionPath = path.join(sessionsRoot, entry.name);
      const session = host.io.readJson(path.join(sessionPath, 'session.json'), SessionRecordSchema);
      return session ? { session, sessionPath } : null;
    })
    .filter((entry): entry is { session: SessionRecord; sessionPath: string } => entry !== null);
}

export function reconcileProjectSessionTitles(
  host: StorageHost,
  project: ProjectRecord,
  normalizeSessionRecord: (session: SessionRecord, sessionPath?: string) => SessionRecord,
): SessionRecord[] {
  const storedSessions = readProjectSessions(host, project);
  const normalizedSessions = storedSessions.map(({ session, sessionPath }) => (
    normalizeSessionRecord(session, sessionPath)
  ));
  const autoGeneratedTitlePattern = /^new session (\d+)$/i;
  const timestampTitlePattern = /^Session \d{4}-\d{2}-\d{2} \d{2}:\d{2}$/;
  const autoSessions = normalizedSessions
    .filter((session) => (
      autoGeneratedTitlePattern.test(session.title.trim()) || timestampTitlePattern.test(session.title.trim())
    ))
    .sort((a, b) => {
      if (a.createdAt !== b.createdAt) {
        return a.createdAt - b.createdAt;
      }
      return a.sessionId.localeCompare(b.sessionId);
    });

  if (autoSessions.length === 0) {
    return normalizedSessions;
  }

  const nextTitlesBySessionId = new Map<string, string>();
  autoSessions.forEach((session, index) => {
    nextTitlesBySessionId.set(session.sessionId, `new session ${index}`);
  });

  let didRewrite = false;
  const rewrittenBySessionId = new Map<string, SessionRecord>();

  for (const { sessionPath } of storedSessions) {
    const session = normalizedSessions.find((entry) => entry.sessionPath === sessionPath);
    if (!session) {
      continue;
    }

    const nextTitle = nextTitlesBySessionId.get(session.sessionId);
    if (nextTitle && session.title !== nextTitle) {
      const rewrittenSession: SessionRecord = {
        ...session,
        title: nextTitle,
      };
      host.io.writeJsonAtomic(path.join(sessionPath, 'session.json'), rewrittenSession);
      rewrittenBySessionId.set(session.sessionId, rewrittenSession);
      didRewrite = true;
      continue;
    }

    rewrittenBySessionId.set(session.sessionId, session);
  }

  if (!didRewrite) {
    return normalizedSessions;
  }

  return normalizedSessions.map((session) => rewrittenBySessionId.get(session.sessionId) ?? session);
}
