import type { TranslationKey } from '../../../i18n';

export const CATALOG_VERB_LABEL_KEYS: Record<string, TranslationKey> = {
  '已读取': 'chat.workProcessVerb.readComplete',
  '正在读取': 'chat.workProcessVerb.readRunning',
  '已列出': 'chat.workProcessVerb.globComplete',
  '正在列出': 'chat.workProcessVerb.globRunning',
  '已搜索代码': 'chat.workProcessVerb.grepComplete',
  '正在搜索代码': 'chat.workProcessVerb.grepRunning',
  '已搜索代码库': 'chat.workProcessVerb.searchCodebaseComplete',
  '正在搜索代码库': 'chat.workProcessVerb.searchCodebaseRunning',
  '已浏览': 'chat.workProcessVerb.webFetchComplete',
  '正在浏览': 'chat.workProcessVerb.webFetchRunning',
  '已联网搜索': 'chat.workProcessVerb.webSearchComplete',
  '正在联网搜索': 'chat.workProcessVerb.webSearchRunning',
  '已运行命令': 'chat.workProcessVerb.bashComplete',
  '正在运行命令': 'chat.workProcessVerb.bashRunning',
  '已写入': 'chat.workProcessVerb.writeComplete',
  '正在写入': 'chat.workProcessVerb.writeRunning',
  '已编辑': 'chat.workProcessVerb.editComplete',
  '正在编辑': 'chat.workProcessVerb.editRunning',
  '已删除': 'chat.workProcessVerb.deleteComplete',
  '正在删除': 'chat.workProcessVerb.deleteRunning',
  '已移动': 'chat.workProcessVerb.moveComplete',
  '正在移动': 'chat.workProcessVerb.moveRunning',
  '已复制': 'chat.workProcessVerb.copyComplete',
  '正在复制': 'chat.workProcessVerb.copyRunning',
  '已编辑 Notebook': 'chat.workProcessVerb.notebookComplete',
  '正在编辑 Notebook': 'chat.workProcessVerb.notebookRunning',
  '已检查状态': 'chat.workProcessVerb.gitStatusComplete',
  '正在检查状态': 'chat.workProcessVerb.gitStatusRunning',
  '已查看差异': 'chat.workProcessVerb.gitDiffComplete',
  '正在查看差异': 'chat.workProcessVerb.gitDiffRunning',
  '已查看历史': 'chat.workProcessVerb.gitLogComplete',
  '正在查看历史': 'chat.workProcessVerb.gitLogRunning',
  '已暂存': 'chat.workProcessVerb.gitAddComplete',
  '正在暂存': 'chat.workProcessVerb.gitAddRunning',
  '已取消暂存': 'chat.workProcessVerb.gitUnstageComplete',
  '正在取消暂存': 'chat.workProcessVerb.gitUnstageRunning',
  '已提交': 'chat.workProcessVerb.gitCommitComplete',
  '正在提交': 'chat.workProcessVerb.gitCommitRunning',
  '已搜索工具': 'chat.workProcessVerb.toolSearchComplete',
  '正在搜索工具': 'chat.workProcessVerb.toolSearchRunning',
  '已准备交接': 'chat.workProcessVerb.handoffComplete',
  '正在准备交接': 'chat.workProcessVerb.handoffRunning',
  '已生成计划': 'chat.workProcessVerb.planComplete',
  '正在生成计划': 'chat.workProcessVerb.planRunning',
  '已读取记忆': 'chat.workProcessVerb.memoryReadComplete',
  '正在读取记忆': 'chat.workProcessVerb.memoryReadRunning',
  '已写入记忆': 'chat.workProcessVerb.memoryWriteComplete',
  '正在写入记忆': 'chat.workProcessVerb.memoryWriteRunning',
  '已删除记忆': 'chat.workProcessVerb.memoryDeleteComplete',
  '正在删除记忆': 'chat.workProcessVerb.memoryDeleteRunning',
  '已列出技能': 'chat.workProcessVerb.skillsComplete',
  '正在列出技能': 'chat.workProcessVerb.skillsRunning',
  '已运行技能': 'chat.workProcessVerb.skillRunComplete',
  '正在运行技能': 'chat.workProcessVerb.skillRunRunning',
  '已查询 MCP': 'chat.workProcessVerb.mcpComplete',
  '正在查询 MCP': 'chat.workProcessVerb.mcpRunning',
  '已读取 RDX 上下文': 'chat.workProcessVerb.rdxContextComplete',
  '正在读取 RDX 上下文': 'chat.workProcessVerb.rdxContextRunning',
  '已调用子代理': 'chat.workProcessVerb.subagentComplete',
  '正在调用子代理': 'chat.workProcessVerb.subagentRunning',
  '已创建任务': 'chat.workProcessVerb.taskCreateComplete',
  '正在创建任务': 'chat.workProcessVerb.taskCreateRunning',
  '已更新任务': 'chat.workProcessVerb.taskUpdateComplete',
  '正在更新任务': 'chat.workProcessVerb.taskUpdateRunning',
  '已读取任务': 'chat.workProcessVerb.taskGetComplete',
  '正在读取任务': 'chat.workProcessVerb.taskGetRunning',
  '已列出任务': 'chat.workProcessVerb.taskListComplete',
  '正在列出任务': 'chat.workProcessVerb.taskListRunning',
  '已停止任务': 'chat.workProcessVerb.taskStopComplete',
  '正在停止任务': 'chat.workProcessVerb.taskStopRunning',
  '询问': 'chat.workProcessGroupAsk',
  '搜索': 'chat.workProcessGroupSearch',
  'Git': 'chat.workProcessGroupGit',
  '命令': 'chat.workProcessGroupCommand',
  '工具发现': 'chat.workProcessGroupToolSearch',
  '产物': 'chat.workProcessGroupArtifact',
  '技能': 'chat.workProcessGroupSkills',
  'MCP': 'chat.workProcessGroupMcp',
  'RDX 上下文': 'chat.workProcessGroupRdx',
  '任务': 'chat.workProcessGroupTask',
  '变更': 'chat.workProcessGroupChange',
  '动作': 'chat.workProcessGroupActionUnit',
};
