export const IPC_HANDLER_DOMAINS = {
  shell: [
    'dialog:selectRdcFiles',
    'dialog:selectFiles',
    'dialog:selectDirectory',
    'window:minimize',
    'window:toggleMaximize',
    'window:close',
    'window:isMaximized',
    'app:getMeta',
    'app:selectAvatar',
    'app:getAvatarDataUrl',
    'app:openPath',
    'app:copyText',
  ],
  conversation: [
    'conversation:sendMessage',
    'conversation:rewriteFromMessage',
    'conversation:getHistory',
    'conversation:switchBranch',
    'conversation:clearHistory',
    'conversation:undoLastTurn',
    'conversation:compactHistory',
    'conversation:cancelActiveTurn',
    'conversation:answerUserInput',
    'conversation:answerToolApproval',
  ],
  workflow: [
    'workflow:getState',
    'workflow:resume',
    'workflow:stop',
    'workflow:getRunUsage',
    'workflow:listRuns',
    'workflow:listActiveRuns',
  ],
  projectSession: [
    'project:list',
    'project:add',
    'project:select',
    'project:rename',
    'project:remove',
    'project:inputs:list',
    'project:inputs:refresh',
    'project:inputs:import',
    'project:inputs:importPaths',
    'session:list',
    'session:create',
    'session:rename',
    'session:remove',
    'session:select',
    'session:attachments:list',
    'session:attachments:import',
    'session:outputs:list',
    'run:list',
  ],
  captureDevice: [
    'capture:list',
    'capture:select',
    'capture:openProjectInput',
    'capture:getOpenedState',
    'capture:clearOpenedState',
    'device:list',
    'device:refresh',
    'device:activate',
  ],
  settingsProfile: [
    'settings:get',
    'settings:getProviderCatalog',
    'settings:getModelCapability',
    'settings:getProviderSecret',
    'settings:importAgentManifest',
    'settings:upsertSkill',
    'settings:deleteSkill',
    'settings:importSkill',
    'settings:upsertMcpServer',
    'settings:deleteMcpServer',
    'settings:importMcpServer',
    'settings:set',
    'llm:configure',
    'llm:testConnection',
    'llm:getAvailableModels',
    'llm:testProviderDraft',
    'llm:connectProvider',
    'llm:refreshProviderModels',
    'llm:disconnectProvider',
    'llm:startProviderAccountLogin',
    'llm:getProviderAccountStatus',
    'llm:finishProviderAccountLogin',
    'llm:logoutProviderAccount',
  ],
  toolsEvidenceRuntime: [
    'tool:getCatalog',
    'tool:getRuntimeSummary',
    'evidence:getChain',
    'evidence:getEvents',
    'runtimeLog:list',
  ],
  terminalContext: [
    'terminal:listTabs',
    'terminal:createTab',
    'terminal:closeTab',
    'terminal:activateTab',
    'terminal:write',
    'terminal:resize',
    'context:get',
    'context:openHumanPreview',
    'context:closeHumanPreview',
  ],
  agent: [
    'agent:sendMessage',
    'agent:getState',
    'agent:getAllStates',
    'agent:configure',
  ],
  memory: [
    'memory:list',
    'memory:get',
    'memory:write',
    'memory:delete',
  ],
  command: [
    'command:list',
    'command:execute',
  ],
  trace: [
    'trace:getRun',
    'trace:getEvents',
    'trace:getProjection',
    'trace:exportRun',
    'trace:switchBranch',
  ],
} as const;

export type IpcHandlerDomain = keyof typeof IPC_HANDLER_DOMAINS;
export type IpcHandlerChannel = (typeof IPC_HANDLER_DOMAINS)[IpcHandlerDomain][number];

export const IPC_EVENT_DOMAINS = {
  shell: ['app:themeChanged', 'window:maximized-changed'],
  conversation: ['conversation:event'],
  workflow: [
    'workflow:stateChanged',
    'workflow:stageChanged',
    'workflow:runStatusChanged',
    'workflow:runUsageChanged',
    'trace:projectionChanged',
    'workflow:blocked',
  ],
  trace: ['trace:eventAdded'],
  agent: ['agent:message', 'agent:statusChanged'],
  toolsEvidenceRuntime: ['tool:executionComplete', 'evidence:eventAdded', 'runtime:logAppended'],
  captureDevice: ['device:statusChanged', 'capture:statusChanged', 'capture:openedStateChanged'],
  projectSession: ['project:inputsChanged'],
  terminalContext: ['context:changed', 'terminal:data', 'terminal:exit', 'terminal:tabsChanged'],
} as const;

export type IpcEventDomain = keyof typeof IPC_EVENT_DOMAINS;
export type IpcEventChannel = (typeof IPC_EVENT_DOMAINS)[IpcEventDomain][number];
