import type { ElectronAPI } from './electron';
export type {
  AgentApi,
  AppMetaApi,
  AppShellApi,
  CaptureApi,
  CommandApi,
  ContextApi,
  ConversationApi,
  DeviceApi,
  DialogApi,
  EventSubscriptionApi,
  EvidenceApi,
  LlmApi,
  InvestigationApi,
  KnowledgeApi,
  MemoryApi,
  McpApi,
  PlatformApi,
  ProjectApi,
  RawChannelSubscriptionApi,
  RunApi,
  RuntimeLogApi,
  SessionApi,
  SettingsApi,
  ToolApi,
  WindowControlsApi,
  WorkflowApi,
} from './electron/index';

export type RendererElectronApi = ElectronAPI;
